version: "3"

services:
  api_go:
    build: ./back
    container_name: api_go
    restart: unless-stoped
    ports:
      - 3100:3100
    environment:
      - HTTP_HOST=${HTTP_HOST}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - TOKEN=${TOKEN}
      - CHAT=${CHAT}
    logging:
      options:
        max-size: 10m
